"""
macro_mapping.py — commodity/FX metadata + which Thai stock tickers each one
affects. Single file, edit here to add/remove commodities or change mappings.
"""

COMMODITIES = {
    "BZ=F": {
        "name_th": "น้ำมันดิบเบรนท์",
        "name_en": "Brent Crude Oil",
        "unit": "USD/บาร์เรล",
        "zone": "energy",
        "tickers": ["PTT", "PTTEP", "TOP", "SPRC", "BCP"],
    },
    "CL=F": {
        "name_th": "น้ำมันดิบ WTI",
        "name_en": "WTI Crude Oil",
        "unit": "USD/บาร์เรล",
        "zone": "energy",
        "tickers": [],
    },
    "NG=F": {
        "name_th": "ก๊าซธรรมชาติ",
        "name_en": "Natural Gas (Henry Hub)",
        "unit": "USD/MMBtu",
        "zone": "energy",
        "tickers": ["GULF", "BGRIM", "GPSC"],
    },
    "HO=F": {
        "name_th": "น้ำมันดีเซล (Heating Oil)",
        "name_en": "Heating Oil / Diesel Proxy",
        "unit": "USD/แกลลอน",
        "zone": "energy",
        "tickers": ["TOP", "SPRC", "BCP", "IRPC", "PTTGC"],
    },
    "RB=F": {
        "name_th": "น้ำมันเบนซิน (RBOB Gasoline)",
        "name_en": "RBOB Gasoline",
        "unit": "USD/แกลลอน",
        "zone": "energy",
        "tickers": ["TOP", "SPRC", "BCP"],
    },
    "HRC=F": {
        "name_th": "เหล็กแผ่นม้วนร้อน",
        "name_en": "US HRC Steel Futures",
        "unit": "USD/ตัน",
        "zone": "industrial",
        "tickers": ["TSTH", "TMT", "BSBM", "PAP", "MILL"],
    },
    "PETRO_HDPE": {
        "name_th": "ส่วนต่างเม็ดพลาสติก HDPE",
        "name_en": "HDPE Polymer Spread",
        "unit": "USD/เมตริกตัน",
        "zone": "industrial",
        "tickers": ["PTTGC", "SCC", "IRPC"],
    },
    "PETRO_PX": {
        "name_th": "ส่วนต่างพารากไซลีน (PX)",
        "name_en": "Paraxylene Petrochem Spread",
        "unit": "USD/เมตริกตัน",
        "zone": "industrial",
        "tickers": ["IVL", "PTTGC", "SCC"],
    },
    "PETRO_PTA": {
        "name_th": "ส่วนต่าง PTA (โพลีเอสเตอร์)",
        "name_en": "PTA Polymer Spread",
        "unit": "USD/เมตริกตัน",
        "zone": "industrial",
        "tickers": ["IVL"],
    },
    "HG=F": {
        "name_th": "ทองแดง",
        "name_en": "Copper Futures",
        "unit": "USD/ปอนด์",
        "zone": "industrial",
        "tickers": ["KCE", "HANA", "DELTA", "SVI"],
    },
    "ALI=F": {
        "name_th": "อลูมิเนียม",
        "name_en": "Aluminum Futures",
        "unit": "USD/เมตริกตัน",
        "zone": "industrial",
        "tickers": ["CBG", "OSP"],
    },
    "SICOM_RSS3": {
        "name_th": "ยางพารา RSS3 (SICOM)",
        "name_en": "SICOM Rubber RSS3",
        "unit": "เซนต์/กก.",
        "zone": "agri",
        "tickers": ["STA", "STGT", "TEGH", "NER", "TRUBB"],
    },
    "SICOM_TSR20": {
        "name_th": "ยางพาราแท่ง TSR20 (SICOM)",
        "name_en": "SICOM Rubber TSR20",
        "unit": "เซนต์/กก.",
        "zone": "agri",
        "tickers": ["STA", "TEGH", "NER"],
    },
    "SHFE_RU": {
        "name_th": "ยางพาราเซี่ยงไฮ้ (SHFE)",
        "name_en": "Shanghai Natural Rubber",
        "unit": "หยวน/เมตริกตัน",
        "zone": "agri",
        "tickers": ["STA", "STGT", "NER", "TEGH"],
    },
    "SB=F": {
        "name_th": "น้ำตาลทรายดิบ #11",
        "name_en": "Sugar #11",
        "unit": "เซนต์/ปอนด์",
        "zone": "agri",
        "tickers": ["KSL", "KTIS", "KBS", "BRR"],
    },
    "ZC=F": {
        "name_th": "ข้าวโพดเลี้ยงสัตว์",
        "name_en": "Corn Futures",
        "unit": "เซนต์/บุชเชล",
        "zone": "agri",
        "tickers": ["CPF", "TFG", "GFPT"],
    },
    "ZS=F": {
        "name_th": "ถั่วเหลือง",
        "name_en": "Soybean",
        "unit": "เซนต์/บุชเชล",
        "zone": "agri",
        "tickers": ["CPF", "TFG", "GFPT", "TVO"],
    },
    "ZM=F": {
        "name_th": "กากถั่วเหลือง",
        "name_en": "Soybean Meal",
        "unit": "USD/short ton",
        "zone": "agri",
        "tickers": ["CPF", "TFG", "GFPT", "TVO"],
    },
    "ZW=F": {
        "name_th": "ข้าวสาลี",
        "name_en": "Wheat Futures",
        "unit": "เซนต์/บุชเชล",
        "zone": "agri",
        "tickers": ["NSL", "PB", "SNNP", "TFM"],
    },
    "CPO=F": {
        "name_th": "น้ำมันปาล์มดิบ (มาเลเซีย)",
        "name_en": "Malaysian Crude Palm Oil",
        "unit": "USD/เมตริกตัน",
        "zone": "agri",
        "tickers": ["UVAN", "UPOIC", "VPO"],
    },
    "HE=F": {
        "name_th": "สุกร (หมูเนื้อแดง Lean Hogs)",
        "name_en": "Lean Hogs Futures",
        "unit": "เซนต์/ปอนด์",
        "zone": "agri",
        "tickers": ["CPF", "TFG", "BTG", "GFPT"],
    },
    "KC=F": {
        "name_th": "กาแฟอาราบิก้า (Coffee)",
        "name_en": "Coffee Arabica Futures",
        "unit": "เซนต์/ปอนด์",
        "zone": "agri",
        "tickers": ["OR", "CBG", "CENTEL", "MINT"],
    },
    "ZL=F": {
        "name_th": "น้ำมันถั่วเหลือง",
        "name_en": "Soybean Oil",
        "unit": "เซนต์/ปอนด์",
        "zone": "agri",
        "tickers": [],
    },
    "GC=F": {
        "name_th": "ทองคำ",
        "name_en": "Gold",
        "unit": "USD/ออนซ์",
        "zone": "financial",
        "tickers": [],
    },
    "THB=X": {
        "name_th": "อัตราแลกเปลี่ยน ดอลลาร์/บาท",
        "name_en": "USD/THB",
        "unit": "บาท/ดอลลาร์",
        "zone": "financial",
        "tickers": ["DELTA", "KCE", "HANA", "AOT"],
    },
    "DX-Y.NYB": {
        "name_th": "ดัชนีดอลลาร์สหรัฐ",
        "name_en": "US Dollar Index (DXY)",
        "unit": "ดัชนี",
        "zone": "financial",
        "tickers": ["DELTA", "KCE", "HANA"],
    },
    "^TNX": {
        "name_th": "อัตราผลตอบแทนพันธบัตร US 10 ปี",
        "name_en": "US 10-Year Treasury Yield",
        "unit": "%",
        "zone": "financial",
        "tickers": ["TLI", "BLA", "KBANK", "BBL", "SCB"],
    },
    "BDRY": {
        "name_th": "ค่าระวางเรือสินค้าแห้ง (BDI ETF)",
        "name_en": "Dry Bulk Freight ETF (BDRY)",
        "unit": "USD/หุ้น",
        "zone": "financial",
        "tickers": ["PSL", "TTA"],
    },
    "ZIM": {
        "name_th": "ค่าระวางเรือตู้คอนเทนเนอร์ (Proxy)",
        "name_en": "Container Shipping Index Proxy",
        "unit": "USD/หุ้น",
        "zone": "financial",
        "tickers": ["RCL", "WICE", "III", "SJWD"],
    },
}

BANK_TICKERS = [
    "BAY", "BBL", "CIMBT", "CREDIT", "KBANK", "KKP",
    "KTB", "LHFG", "SCB", "TCAP", "TISCO", "TTB",
]

ZONE_LABELS = {
    "energy": "พลังงาน",
    "agri": "เกษตร-อาหาร",
    "industrial": "โลหะ-อุตสาหกรรม",
    "financial": "การเงิน-ดอกเบี้ย",
}
